# [[keyboard.bindings]]
# key = ""
# mods = "None"
# chars = ""

#[keyboard]
#bindings = [
#  { key = "V", mods = "Control", action = "Paste" },
#  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance"}, # `Ctrl+D` to close
#]

[font]

normal.family = "CaskaydiaCove NF"
bold.family = "CaskaydiaCove NF"
italic.family = "CaskaydiaCove NF"
bold_italic.family = "CaskaydiaCove NF"

size = 16.0

[colors]
    draw_bold_text_with_bright_colors = true
    

    [colors.bright]
        black   = "#625e4c"
        blue    = "#5b8eff"    # Slightly brighter blue
        cyan    = "#62d6e8"    # A bluer cyan
        green   = "#98e024"
        magenta = "#f4005f"
        red     = "#f4005f"
        white   = "#f6f6ef"
        yellow  = "#e0d561"

    [colors.normal]
        black   = "#1a1a1a"
        blue    = "#5b8eff"    # Updated to match bright blue
        cyan    = "#62d6e8"    # Updated to match bright cyan
        green   = "#98e024"
        magenta = "#f4005f"
        red     = "#f4005f"
        white   = "#c4c5b5"
        yellow  = "#fa8419"


##    [colors.bright]
##        black   = "#625e4c"
##        blue    = "#9d65ff"
##        cyan    = "#58d1eb"
##        green   = "#98e024"
##        magenta = "#f4005f"
##        red     = "#f4005f"
##        white   = "#f6f6ef"
##        yellow  = "#e0d561"
##
##    [colors.normal]
##        black   = "#1a1a1a"
##        blue    = "#9d65ff"
##        cyan    = "#58d1eb"
##        green   = "#98e024"
##        magenta = "#f4005f"
##        red     = "#f4005f"
##        white   = "#c4c5b5"
##        yellow  = "#fa8419"

[window]
opacity = 0.85

[terminal.shell]
program = "/usr/local/bin/zsh"
